CREATE DATABASE JOINS;
USE JOINS;

CREATE TABLE DANCE
    (ID INT PRIMARY KEY,
     NAME VARCHAR(20));

INSERT INTO DANCE VALUES
    (1,'ARNOLD'),
    (2,'BOB'),
    (3,'CAT'),
    (4,'DOG');

CREATE TABLE MUSIC
    (ID INT PRIMARY KEY,
     NAME VARCHAR(20));

INSERT INTO MUSIC VALUES
    (3,'CAT'),
    (4,'DOG'),
    (5,'LION'),
    (6,'BEAR');

SELECT * FROM DANCE;
SELECT * FROM MUSIC;

SELECT NAME AS FULLNAME FROM MUSIC;

UPDATE MUSIC SET name='katty perry' WHERE ID=3;
UPDATE MUSIC SET name='snoopdog' WHERE ID=4;
SELECT * FROM MUSIC;

SELECT D.ID,D.NAME,M.NAME
    FROM DANCE AS D
    JOIN MUSIC AS M
    ON D.ID = M.ID;


SELECT D.ID,D.NAME AS DANCE_NAME,M.NAME AS MUSIC_NAME
    FROM DANCE AS D
    LEFT JOIN MUSIC AS M
    ON D.ID = M.ID;

SELECT D.ID,D.NAME AS DANCE_NAME,M.NAME AS MUSIC_NAME
    FROM MUSIC AS M
    RIGHT JOIN DANCE AS D
    ON D.ID = M.ID;

USE catto;

SELECT E1.FIRST_NAME,E2.FIRST_NAME
    FROM
    EMPLOYEE AS E1
    JOIN
    EMPLOYEE AS E2
    ON E1.SUPER_ID = E2.EMP_ID;

SELECT E1.FIRST_NAME AS EMPLOYEE_NAME,E2.FIRST_NAME AS BOSS_NAME
    FROM
    EMPLOYEE AS E1
    JOIN
    EMPLOYEE AS E2
    ON E1.SUPER_ID = E2.EMP_ID;

SELECT B1.branch_name,E1.first_name
    FROM
    EMPLOYEE AS E1
    JOIN
    BRANCH AS B1
    ON B1.mgr_id = E1.emp_id;

USE CLASSICMODELS;
DESC ORDERDETAILS;

SELECT ORDERNUMBER,SUM(QUANTITYORDERED) AS ITEMCOUNT,
    SUM(PRICEEACH*QUANTITYORDERED) AS TOTAL
    FROM
    ORDERDETAILS
    GROUP BY ORDERNUMBER HAVING TOTAL>55000;
